import { ThemeProvider } from "@/theme/theme-provider";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Dream Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${archivo.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="#734cf7" showSpinner={false} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
